[tool.poetry]
name = "524_individual_Python"
version = "0.1.0"
description = "A sample Python package"
authors = ["Ethan Fang <ethanff@student.ubc.ca>"]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"